import 'package:flutter/material.dart';
import '../models/traffic_sign.dart';

// Generated from assets/road_signs_info/manifest.json.
// Run scripts/generate_info_signs_dart.ps1 after manifest updates.
const List<TrafficSign> chinaInformationSigns = <TrafficSign>[
  TrafficSign(
    id: 'info-cn-001',
    name: 'China road sign 路 15.svg',
    code: 'GB 5768.2-2022',
    category: SignCategory.information,
    shape: SignShape.rectangle,
    primaryColor: Color(0xFF1A5FB4),
    secondaryColor: Color(0xFFFFFFFF),
    assetPath: 'assets/road_signs_info/svg/China_road_sign_路_15.svg',
    description:
        'https://upload.wikimedia.org/wikipedia/commons/6/6d/China_road_sign_%E8%B7%AF_15.svg',
  ),
  TrafficSign(
    id: 'info-cn-002',
    name: 'China road sign 路 16.svg',
    code: 'GB 5768.2-2022',
    category: SignCategory.information,
    shape: SignShape.rectangle,
    primaryColor: Color(0xFF1A5FB4),
    secondaryColor: Color(0xFFFFFFFF),
    assetPath: 'assets/road_signs_info/svg/China_road_sign_路_16.svg',
    description:
        'https://upload.wikimedia.org/wikipedia/commons/e/e3/China_road_sign_%E8%B7%AF_16.svg',
  ),
  TrafficSign(
    id: 'info-cn-003',
    name: 'China road sign 路 17a.svg',
    code: 'GB 5768.2-2022',
    category: SignCategory.information,
    shape: SignShape.rectangle,
    primaryColor: Color(0xFF1A5FB4),
    secondaryColor: Color(0xFFFFFFFF),
    assetPath: 'assets/road_signs_info/svg/China_road_sign_路_17a.svg',
    description:
        'https://upload.wikimedia.org/wikipedia/commons/e/e5/China_road_sign_%E8%B7%AF_17a.svg',
  ),
  TrafficSign(
    id: 'info-cn-004',
    name: 'China road sign 路 17b.svg',
    code: 'GB 5768.2-2022',
    category: SignCategory.information,
    shape: SignShape.rectangle,
    primaryColor: Color(0xFF1A5FB4),
    secondaryColor: Color(0xFFFFFFFF),
    assetPath: 'assets/road_signs_info/svg/China_road_sign_路_17b.svg',
    description:
        'https://upload.wikimedia.org/wikipedia/commons/d/d6/China_road_sign_%E8%B7%AF_17b.svg',
  ),
  TrafficSign(
    id: 'info-cn-005',
    name: 'China road sign 路 17c.svg',
    code: 'GB 5768.2-2022',
    category: SignCategory.information,
    shape: SignShape.rectangle,
    primaryColor: Color(0xFF1A5FB4),
    secondaryColor: Color(0xFFFFFFFF),
    assetPath: 'assets/road_signs_info/svg/China_road_sign_路_17c.svg',
    description:
        'https://upload.wikimedia.org/wikipedia/commons/f/f8/China_road_sign_%E8%B7%AF_17c.svg',
  ),
  TrafficSign(
    id: 'info-cn-006',
    name: 'China road sign 路 18.svg',
    code: 'GB 5768.2-2022',
    category: SignCategory.information,
    shape: SignShape.rectangle,
    primaryColor: Color(0xFF1A5FB4),
    secondaryColor: Color(0xFFFFFFFF),
    assetPath: 'assets/road_signs_info/svg/China_road_sign_路_18.svg',
    description:
        'https://upload.wikimedia.org/wikipedia/commons/e/e3/China_road_sign_%E8%B7%AF_18.svg',
  ),
  TrafficSign(
    id: 'info-cn-007',
    name: 'China road sign 路 19.svg',
    code: 'GB 5768.2-2022',
    category: SignCategory.information,
    shape: SignShape.rectangle,
    primaryColor: Color(0xFF1A5FB4),
    secondaryColor: Color(0xFFFFFFFF),
    assetPath: 'assets/road_signs_info/svg/China_road_sign_路_19.svg',
    description:
        'https://upload.wikimedia.org/wikipedia/commons/7/77/China_road_sign_%E8%B7%AF_19.svg',
  ),
  TrafficSign(
    id: 'info-cn-008',
    name: 'China road sign 路 1a.svg',
    code: 'GB 5768.2-2022',
    category: SignCategory.information,
    shape: SignShape.rectangle,
    primaryColor: Color(0xFF1A5FB4),
    secondaryColor: Color(0xFFFFFFFF),
    assetPath: 'assets/road_signs_info/svg/China_road_sign_路_1a.svg',
    description:
        'https://upload.wikimedia.org/wikipedia/commons/3/39/China_road_sign_%E8%B7%AF_1a.svg',
  ),
  TrafficSign(
    id: 'info-cn-009',
    name: 'China road sign 路 20a.svg',
    code: 'GB 5768.2-2022',
    category: SignCategory.information,
    shape: SignShape.rectangle,
    primaryColor: Color(0xFF1A5FB4),
    secondaryColor: Color(0xFFFFFFFF),
    assetPath: 'assets/road_signs_info/svg/China_road_sign_路_20a.svg',
    description:
        'https://upload.wikimedia.org/wikipedia/commons/8/87/China_road_sign_%E8%B7%AF_20a.svg',
  ),
  TrafficSign(
    id: 'info-cn-010',
    name: 'China road sign 路 20b.svg',
    code: 'GB 5768.2-2022',
    category: SignCategory.information,
    shape: SignShape.rectangle,
    primaryColor: Color(0xFF1A5FB4),
    secondaryColor: Color(0xFFFFFFFF),
    assetPath: 'assets/road_signs_info/svg/China_road_sign_路_20b.svg',
    description:
        'https://upload.wikimedia.org/wikipedia/commons/d/d0/China_road_sign_%E8%B7%AF_20b.svg',
  ),
  TrafficSign(
    id: 'info-cn-011',
    name: 'China road sign 路 21a.svg',
    code: 'GB 5768.2-2022',
    category: SignCategory.information,
    shape: SignShape.rectangle,
    primaryColor: Color(0xFF1A5FB4),
    secondaryColor: Color(0xFFFFFFFF),
    assetPath: 'assets/road_signs_info/svg/China_road_sign_路_21a.svg',
    description:
        'https://upload.wikimedia.org/wikipedia/commons/c/c3/China_road_sign_%E8%B7%AF_21a.svg',
  ),
  TrafficSign(
    id: 'info-cn-012',
    name: 'China road sign 路 22a.svg',
    code: 'GB 5768.2-2022',
    category: SignCategory.information,
    shape: SignShape.rectangle,
    primaryColor: Color(0xFF1A5FB4),
    secondaryColor: Color(0xFFFFFFFF),
    assetPath: 'assets/road_signs_info/svg/China_road_sign_路_22a.svg',
    description:
        'https://upload.wikimedia.org/wikipedia/commons/6/62/China_road_sign_%E8%B7%AF_22a.svg',
  ),
  TrafficSign(
    id: 'info-cn-013',
    name: 'China road sign 路 22b.svg',
    code: 'GB 5768.2-2022',
    category: SignCategory.information,
    shape: SignShape.rectangle,
    primaryColor: Color(0xFF1A5FB4),
    secondaryColor: Color(0xFFFFFFFF),
    assetPath: 'assets/road_signs_info/svg/China_road_sign_路_22b.svg',
    description:
        'https://upload.wikimedia.org/wikipedia/commons/f/fa/China_road_sign_%E8%B7%AF_22b.svg',
  ),
  TrafficSign(
    id: 'info-cn-014',
    name: 'China road sign 路 24.svg',
    code: 'GB 5768.2-2022',
    category: SignCategory.information,
    shape: SignShape.rectangle,
    primaryColor: Color(0xFF1A5FB4),
    secondaryColor: Color(0xFFFFFFFF),
    assetPath: 'assets/road_signs_info/svg/China_road_sign_路_24.svg',
    description:
        'https://upload.wikimedia.org/wikipedia/commons/c/c0/China_road_sign_%E8%B7%AF_24.svg',
  ),
  TrafficSign(
    id: 'info-cn-015',
    name: 'China road sign 路 25.svg',
    code: 'GB 5768.2-2022',
    category: SignCategory.information,
    shape: SignShape.rectangle,
    primaryColor: Color(0xFF1A5FB4),
    secondaryColor: Color(0xFFFFFFFF),
    assetPath: 'assets/road_signs_info/svg/China_road_sign_路_25.svg',
    description:
        'https://upload.wikimedia.org/wikipedia/commons/4/44/China_road_sign_%E8%B7%AF_25.svg',
  ),
  TrafficSign(
    id: 'info-cn-016',
    name: 'China road sign 路 26.svg',
    code: 'GB 5768.2-2022',
    category: SignCategory.information,
    shape: SignShape.rectangle,
    primaryColor: Color(0xFF1A5FB4),
    secondaryColor: Color(0xFFFFFFFF),
    assetPath: 'assets/road_signs_info/svg/China_road_sign_路_26.svg',
    description:
        'https://upload.wikimedia.org/wikipedia/commons/5/5c/China_road_sign_%E8%B7%AF_26.svg',
  ),
  TrafficSign(
    id: 'info-cn-017',
    name: 'China road sign 路 2a.svg',
    code: 'GB 5768.2-2022',
    category: SignCategory.information,
    shape: SignShape.rectangle,
    primaryColor: Color(0xFF1A5FB4),
    secondaryColor: Color(0xFFFFFFFF),
    assetPath: 'assets/road_signs_info/svg/China_road_sign_路_2a.svg',
    description:
        'https://upload.wikimedia.org/wikipedia/commons/2/20/China_road_sign_%E8%B7%AF_2a.svg',
  ),
  TrafficSign(
    id: 'info-cn-018',
    name: 'China road sign 路 31.svg',
    code: 'GB 5768.2-2022',
    category: SignCategory.information,
    shape: SignShape.rectangle,
    primaryColor: Color(0xFF1A5FB4),
    secondaryColor: Color(0xFFFFFFFF),
    assetPath: 'assets/road_signs_info/svg/China_road_sign_路_31.svg',
    description:
        'https://upload.wikimedia.org/wikipedia/commons/1/1f/China_road_sign_%E8%B7%AF_31.svg',
  ),
  TrafficSign(
    id: 'info-cn-019',
    name: 'China road sign 路 34.svg',
    code: 'GB 5768.2-2022',
    category: SignCategory.information,
    shape: SignShape.rectangle,
    primaryColor: Color(0xFF1A5FB4),
    secondaryColor: Color(0xFFFFFFFF),
    assetPath: 'assets/road_signs_info/svg/China_road_sign_路_34.svg',
    description:
        'https://upload.wikimedia.org/wikipedia/commons/b/b9/China_road_sign_%E8%B7%AF_34.svg',
  ),
  TrafficSign(
    id: 'info-cn-020',
    name: 'China road sign 路 35a.svg',
    code: 'GB 5768.2-2022',
    category: SignCategory.information,
    shape: SignShape.rectangle,
    primaryColor: Color(0xFF1A5FB4),
    secondaryColor: Color(0xFFFFFFFF),
    assetPath: 'assets/road_signs_info/svg/China_road_sign_路_35a.svg',
    description:
        'https://upload.wikimedia.org/wikipedia/commons/8/80/China_road_sign_%E8%B7%AF_35a.svg',
  ),
  TrafficSign(
    id: 'info-cn-021',
    name: 'China road sign 路 35b.svg',
    code: 'GB 5768.2-2022',
    category: SignCategory.information,
    shape: SignShape.rectangle,
    primaryColor: Color(0xFF1A5FB4),
    secondaryColor: Color(0xFFFFFFFF),
    assetPath: 'assets/road_signs_info/svg/China_road_sign_路_35b.svg',
    description:
        'https://upload.wikimedia.org/wikipedia/commons/5/5a/China_road_sign_%E8%B7%AF_35b.svg',
  ),
  TrafficSign(
    id: 'info-cn-022',
    name: 'China road sign 路 36a (Blue and white).svg',
    code: 'GB 5768.2-2022',
    category: SignCategory.information,
    shape: SignShape.rectangle,
    primaryColor: Color(0xFF1A5FB4),
    secondaryColor: Color(0xFFFFFFFF),
    assetPath:
        'assets/road_signs_info/svg/China_road_sign_路_36a_(Blue_and_white).svg',
    description:
        'https://upload.wikimedia.org/wikipedia/commons/a/a4/China_road_sign_%E8%B7%AF_36a_%28Blue_and_white%29.svg',
  ),
  TrafficSign(
    id: 'info-cn-023',
    name: 'China road sign 路 36a (Green and white).svg',
    code: 'GB 5768.2-2022',
    category: SignCategory.information,
    shape: SignShape.rectangle,
    primaryColor: Color(0xFF1A5FB4),
    secondaryColor: Color(0xFFFFFFFF),
    assetPath:
        'assets/road_signs_info/svg/China_road_sign_路_36a_(Green_and_white).svg',
    description:
        'https://upload.wikimedia.org/wikipedia/commons/5/5f/China_road_sign_%E8%B7%AF_36a_%28Green_and_white%29.svg',
  ),
  TrafficSign(
    id: 'info-cn-024',
    name: 'China road sign 路 36b (Blue and white).svg',
    code: 'GB 5768.2-2022',
    category: SignCategory.information,
    shape: SignShape.rectangle,
    primaryColor: Color(0xFF1A5FB4),
    secondaryColor: Color(0xFFFFFFFF),
    assetPath:
        'assets/road_signs_info/svg/China_road_sign_路_36b_(Blue_and_white).svg',
    description:
        'https://upload.wikimedia.org/wikipedia/commons/7/77/China_road_sign_%E8%B7%AF_36b_%28Blue_and_white%29.svg',
  ),
  TrafficSign(
    id: 'info-cn-025',
    name: 'China road sign 路 36b (Green and white).svg',
    code: 'GB 5768.2-2022',
    category: SignCategory.information,
    shape: SignShape.rectangle,
    primaryColor: Color(0xFF1A5FB4),
    secondaryColor: Color(0xFFFFFFFF),
    assetPath:
        'assets/road_signs_info/svg/China_road_sign_路_36b_(Green_and_white).svg',
    description:
        'https://upload.wikimedia.org/wikipedia/commons/e/e6/China_road_sign_%E8%B7%AF_36b_%28Green_and_white%29.svg',
  ),
  TrafficSign(
    id: 'info-cn-026',
    name: 'China road sign 路 37a2 (Blue and white).svg',
    code: 'GB 5768.2-2022',
    category: SignCategory.information,
    shape: SignShape.rectangle,
    primaryColor: Color(0xFF1A5FB4),
    secondaryColor: Color(0xFFFFFFFF),
    assetPath:
        'assets/road_signs_info/svg/China_road_sign_路_37a2_(Blue_and_white).svg',
    description:
        'https://upload.wikimedia.org/wikipedia/commons/2/26/China_road_sign_%E8%B7%AF_37a2_%28Blue_and_white%29.svg',
  ),
  TrafficSign(
    id: 'info-cn-027',
    name: 'China road sign 路 37a2 (Green and white).svg',
    code: 'GB 5768.2-2022',
    category: SignCategory.information,
    shape: SignShape.rectangle,
    primaryColor: Color(0xFF1A5FB4),
    secondaryColor: Color(0xFFFFFFFF),
    assetPath:
        'assets/road_signs_info/svg/China_road_sign_路_37a2_(Green_and_white).svg',
    description:
        'https://upload.wikimedia.org/wikipedia/commons/e/e4/China_road_sign_%E8%B7%AF_37a2_%28Green_and_white%29.svg',
  ),
  TrafficSign(
    id: 'info-cn-028',
    name: 'China road sign 路 37b2 (Blue and white).svg',
    code: 'GB 5768.2-2022',
    category: SignCategory.information,
    shape: SignShape.rectangle,
    primaryColor: Color(0xFF1A5FB4),
    secondaryColor: Color(0xFFFFFFFF),
    assetPath:
        'assets/road_signs_info/svg/China_road_sign_路_37b2_(Blue_and_white).svg',
    description:
        'https://upload.wikimedia.org/wikipedia/commons/1/16/China_road_sign_%E8%B7%AF_37b2_%28Blue_and_white%29.svg',
  ),
  TrafficSign(
    id: 'info-cn-029',
    name: 'China road sign 路 37b2 (Green and white).svg',
    code: 'GB 5768.2-2022',
    category: SignCategory.information,
    shape: SignShape.rectangle,
    primaryColor: Color(0xFF1A5FB4),
    secondaryColor: Color(0xFFFFFFFF),
    assetPath:
        'assets/road_signs_info/svg/China_road_sign_路_37b2_(Green_and_white).svg',
    description:
        'https://upload.wikimedia.org/wikipedia/commons/b/b8/China_road_sign_%E8%B7%AF_37b2_%28Green_and_white%29.svg',
  ),
  TrafficSign(
    id: 'info-cn-030',
    name: 'China road sign 路 37c (Blue and white).svg',
    code: 'GB 5768.2-2022',
    category: SignCategory.information,
    shape: SignShape.rectangle,
    primaryColor: Color(0xFF1A5FB4),
    secondaryColor: Color(0xFFFFFFFF),
    assetPath:
        'assets/road_signs_info/svg/China_road_sign_路_37c_(Blue_and_white).svg',
    description:
        'https://upload.wikimedia.org/wikipedia/commons/f/f9/China_road_sign_%E8%B7%AF_37c_%28Blue_and_white%29.svg',
  ),
  TrafficSign(
    id: 'info-cn-031',
    name: 'China road sign 路 37c (Green and white).svg',
    code: 'GB 5768.2-2022',
    category: SignCategory.information,
    shape: SignShape.rectangle,
    primaryColor: Color(0xFF1A5FB4),
    secondaryColor: Color(0xFFFFFFFF),
    assetPath:
        'assets/road_signs_info/svg/China_road_sign_路_37c_(Green_and_white).svg',
    description:
        'https://upload.wikimedia.org/wikipedia/commons/7/75/China_road_sign_%E8%B7%AF_37c_%28Green_and_white%29.svg',
  ),
  TrafficSign(
    id: 'info-cn-032',
    name: 'China road sign 路 3a.svg',
    code: 'GB 5768.2-2022',
    category: SignCategory.information,
    shape: SignShape.rectangle,
    primaryColor: Color(0xFF1A5FB4),
    secondaryColor: Color(0xFFFFFFFF),
    assetPath: 'assets/road_signs_info/svg/China_road_sign_路_3a.svg',
    description:
        'https://upload.wikimedia.org/wikipedia/commons/7/79/China_road_sign_%E8%B7%AF_3a.svg',
  ),
  TrafficSign(
    id: 'info-cn-033',
    name: 'China road sign 路 3b.svg',
    code: 'GB 5768.2-2022',
    category: SignCategory.information,
    shape: SignShape.rectangle,
    primaryColor: Color(0xFF1A5FB4),
    secondaryColor: Color(0xFFFFFFFF),
    assetPath: 'assets/road_signs_info/svg/China_road_sign_路_3b.svg',
    description:
        'https://upload.wikimedia.org/wikipedia/commons/0/0d/China_road_sign_%E8%B7%AF_3b.svg',
  ),
  TrafficSign(
    id: 'info-cn-034',
    name: 'China road sign 路 45.svg',
    code: 'GB 5768.2-2022',
    category: SignCategory.information,
    shape: SignShape.rectangle,
    primaryColor: Color(0xFF1A5FB4),
    secondaryColor: Color(0xFFFFFFFF),
    assetPath: 'assets/road_signs_info/svg/China_road_sign_路_45.svg',
    description:
        'https://upload.wikimedia.org/wikipedia/commons/5/50/China_road_sign_%E8%B7%AF_45.svg',
  ),
  TrafficSign(
    id: 'info-cn-035',
    name: 'China road sign 路 46a.svg',
    code: 'GB 5768.2-2022',
    category: SignCategory.information,
    shape: SignShape.rectangle,
    primaryColor: Color(0xFF1A5FB4),
    secondaryColor: Color(0xFFFFFFFF),
    assetPath: 'assets/road_signs_info/svg/China_road_sign_路_46a.svg',
    description:
        'https://upload.wikimedia.org/wikipedia/commons/8/82/China_road_sign_%E8%B7%AF_46a.svg',
  ),
  TrafficSign(
    id: 'info-cn-036',
    name: 'China road sign 路 46b.svg',
    code: 'GB 5768.2-2022',
    category: SignCategory.information,
    shape: SignShape.rectangle,
    primaryColor: Color(0xFF1A5FB4),
    secondaryColor: Color(0xFFFFFFFF),
    assetPath: 'assets/road_signs_info/svg/China_road_sign_路_46b.svg',
    description:
        'https://upload.wikimedia.org/wikipedia/commons/e/e6/China_road_sign_%E8%B7%AF_46b.svg',
  ),
  TrafficSign(
    id: 'info-cn-037',
    name: 'China road sign 路 47a.svg',
    code: 'GB 5768.2-2022',
    category: SignCategory.information,
    shape: SignShape.rectangle,
    primaryColor: Color(0xFF1A5FB4),
    secondaryColor: Color(0xFFFFFFFF),
    assetPath: 'assets/road_signs_info/svg/China_road_sign_路_47a.svg',
    description:
        'https://upload.wikimedia.org/wikipedia/commons/6/6e/China_road_sign_%E8%B7%AF_47a.svg',
  ),
  TrafficSign(
    id: 'info-cn-038',
    name: 'China road sign 路 47b.svg',
    code: 'GB 5768.2-2022',
    category: SignCategory.information,
    shape: SignShape.rectangle,
    primaryColor: Color(0xFF1A5FB4),
    secondaryColor: Color(0xFFFFFFFF),
    assetPath: 'assets/road_signs_info/svg/China_road_sign_路_47b.svg',
    description:
        'https://upload.wikimedia.org/wikipedia/commons/0/0a/China_road_sign_%E8%B7%AF_47b.svg',
  ),
  TrafficSign(
    id: 'info-cn-039',
    name: 'China road sign 路 47c.svg',
    code: 'GB 5768.2-2022',
    category: SignCategory.information,
    shape: SignShape.rectangle,
    primaryColor: Color(0xFF1A5FB4),
    secondaryColor: Color(0xFFFFFFFF),
    assetPath: 'assets/road_signs_info/svg/China_road_sign_路_47c.svg',
    description:
        'https://upload.wikimedia.org/wikipedia/commons/0/0e/China_road_sign_%E8%B7%AF_47c.svg',
  ),
  TrafficSign(
    id: 'info-cn-040',
    name: 'China road sign 路 49a.svg',
    code: 'GB 5768.2-2022',
    category: SignCategory.information,
    shape: SignShape.rectangle,
    primaryColor: Color(0xFF1A5FB4),
    secondaryColor: Color(0xFFFFFFFF),
    assetPath: 'assets/road_signs_info/svg/China_road_sign_路_49a.svg',
    description:
        'https://upload.wikimedia.org/wikipedia/commons/8/8f/China_road_sign_%E8%B7%AF_49a.svg',
  ),
  TrafficSign(
    id: 'info-cn-041',
    name: 'China road sign 路 49b.svg',
    code: 'GB 5768.2-2022',
    category: SignCategory.information,
    shape: SignShape.rectangle,
    primaryColor: Color(0xFF1A5FB4),
    secondaryColor: Color(0xFFFFFFFF),
    assetPath: 'assets/road_signs_info/svg/China_road_sign_路_49b.svg',
    description:
        'https://upload.wikimedia.org/wikipedia/commons/d/db/China_road_sign_%E8%B7%AF_49b.svg',
  ),
  TrafficSign(
    id: 'info-cn-042',
    name: 'China road sign 路 4a.svg',
    code: 'GB 5768.2-2022',
    category: SignCategory.information,
    shape: SignShape.rectangle,
    primaryColor: Color(0xFF1A5FB4),
    secondaryColor: Color(0xFFFFFFFF),
    assetPath: 'assets/road_signs_info/svg/China_road_sign_路_4a.svg',
    description:
        'https://upload.wikimedia.org/wikipedia/commons/7/79/China_road_sign_%E8%B7%AF_4a.svg',
  ),
  TrafficSign(
    id: 'info-cn-043',
    name: 'China road sign 路 4b.svg',
    code: 'GB 5768.2-2022',
    category: SignCategory.information,
    shape: SignShape.rectangle,
    primaryColor: Color(0xFF1A5FB4),
    secondaryColor: Color(0xFFFFFFFF),
    assetPath: 'assets/road_signs_info/svg/China_road_sign_路_4b.svg',
    description:
        'https://upload.wikimedia.org/wikipedia/commons/3/32/China_road_sign_%E8%B7%AF_4b.svg',
  ),
  TrafficSign(
    id: 'info-cn-044',
    name: 'China road sign 路 53-2.svg',
    code: 'GB 5768.2-2022',
    category: SignCategory.information,
    shape: SignShape.rectangle,
    primaryColor: Color(0xFF1A5FB4),
    secondaryColor: Color(0xFFFFFFFF),
    assetPath: 'assets/road_signs_info/svg/China_road_sign_路_53-2.svg',
    description:
        'https://upload.wikimedia.org/wikipedia/commons/2/27/China_road_sign_%E8%B7%AF_53-2.svg',
  ),
  TrafficSign(
    id: 'info-cn-045',
    name: 'China road sign 路 53a.svg',
    code: 'GB 5768.2-2022',
    category: SignCategory.information,
    shape: SignShape.rectangle,
    primaryColor: Color(0xFF1A5FB4),
    secondaryColor: Color(0xFFFFFFFF),
    assetPath: 'assets/road_signs_info/svg/China_road_sign_路_53a.svg',
    description:
        'https://upload.wikimedia.org/wikipedia/commons/c/c4/China_road_sign_%E8%B7%AF_53a.svg',
  ),
  TrafficSign(
    id: 'info-cn-046',
    name: 'China road sign 路 53b.svg',
    code: 'GB 5768.2-2022',
    category: SignCategory.information,
    shape: SignShape.rectangle,
    primaryColor: Color(0xFF1A5FB4),
    secondaryColor: Color(0xFFFFFFFF),
    assetPath: 'assets/road_signs_info/svg/China_road_sign_路_53b.svg',
    description:
        'https://upload.wikimedia.org/wikipedia/commons/e/ee/China_road_sign_%E8%B7%AF_53b.svg',
  ),
  TrafficSign(
    id: 'info-cn-047',
    name: 'China road sign 路 54a.svg',
    code: 'GB 5768.2-2022',
    category: SignCategory.information,
    shape: SignShape.rectangle,
    primaryColor: Color(0xFF1A5FB4),
    secondaryColor: Color(0xFFFFFFFF),
    assetPath: 'assets/road_signs_info/svg/China_road_sign_路_54a.svg',
    description:
        'https://upload.wikimedia.org/wikipedia/commons/1/10/China_road_sign_%E8%B7%AF_54a.svg',
  ),
  TrafficSign(
    id: 'info-cn-048',
    name: 'China road sign 路 55.svg',
    code: 'GB 5768.2-2022',
    category: SignCategory.information,
    shape: SignShape.rectangle,
    primaryColor: Color(0xFF1A5FB4),
    secondaryColor: Color(0xFFFFFFFF),
    assetPath: 'assets/road_signs_info/svg/China_road_sign_路_55.svg',
    description:
        'https://upload.wikimedia.org/wikipedia/commons/b/bd/China_road_sign_%E8%B7%AF_55.svg',
  ),
  TrafficSign(
    id: 'info-cn-049',
    name: 'China road sign 路 56-2.svg',
    code: 'GB 5768.2-2022',
    category: SignCategory.information,
    shape: SignShape.rectangle,
    primaryColor: Color(0xFF1A5FB4),
    secondaryColor: Color(0xFFFFFFFF),
    assetPath: 'assets/road_signs_info/svg/China_road_sign_路_56-2.svg',
    description:
        'https://upload.wikimedia.org/wikipedia/commons/a/a8/China_road_sign_%E8%B7%AF_56-2.svg',
  ),
  TrafficSign(
    id: 'info-cn-050',
    name: 'China road sign 路 56a.svg',
    code: 'GB 5768.2-2022',
    category: SignCategory.information,
    shape: SignShape.rectangle,
    primaryColor: Color(0xFF1A5FB4),
    secondaryColor: Color(0xFFFFFFFF),
    assetPath: 'assets/road_signs_info/svg/China_road_sign_路_56a.svg',
    description:
        'https://upload.wikimedia.org/wikipedia/commons/d/d1/China_road_sign_%E8%B7%AF_56a.svg',
  ),
  TrafficSign(
    id: 'info-cn-051',
    name: 'China road sign 路 56b.svg',
    code: 'GB 5768.2-2022',
    category: SignCategory.information,
    shape: SignShape.rectangle,
    primaryColor: Color(0xFF1A5FB4),
    secondaryColor: Color(0xFFFFFFFF),
    assetPath: 'assets/road_signs_info/svg/China_road_sign_路_56b.svg',
    description:
        'https://upload.wikimedia.org/wikipedia/commons/d/d6/China_road_sign_%E8%B7%AF_56b.svg',
  ),
  TrafficSign(
    id: 'info-cn-052',
    name: 'China road sign 路 60.svg',
    code: 'GB 5768.2-2022',
    category: SignCategory.information,
    shape: SignShape.rectangle,
    primaryColor: Color(0xFF1A5FB4),
    secondaryColor: Color(0xFFFFFFFF),
    assetPath: 'assets/road_signs_info/svg/China_road_sign_路_60.svg',
    description:
        'https://upload.wikimedia.org/wikipedia/commons/e/e4/China_road_sign_%E8%B7%AF_60.svg',
  ),
  TrafficSign(
    id: 'info-cn-053',
    name: 'China road sign 路 61a.svg',
    code: 'GB 5768.2-2022',
    category: SignCategory.information,
    shape: SignShape.rectangle,
    primaryColor: Color(0xFF1A5FB4),
    secondaryColor: Color(0xFFFFFFFF),
    assetPath: 'assets/road_signs_info/svg/China_road_sign_路_61a.svg',
    description:
        'https://upload.wikimedia.org/wikipedia/commons/6/65/China_road_sign_%E8%B7%AF_61a.svg',
  ),
  TrafficSign(
    id: 'info-cn-054',
    name: 'China road sign 路 61b.svg',
    code: 'GB 5768.2-2022',
    category: SignCategory.information,
    shape: SignShape.rectangle,
    primaryColor: Color(0xFF1A5FB4),
    secondaryColor: Color(0xFFFFFFFF),
    assetPath: 'assets/road_signs_info/svg/China_road_sign_路_61b.svg',
    description:
        'https://upload.wikimedia.org/wikipedia/commons/8/8a/China_road_sign_%E8%B7%AF_61b.svg',
  ),
  TrafficSign(
    id: 'info-cn-055',
    name: 'China road sign 路 61c.svg',
    code: 'GB 5768.2-2022',
    category: SignCategory.information,
    shape: SignShape.rectangle,
    primaryColor: Color(0xFF1A5FB4),
    secondaryColor: Color(0xFFFFFFFF),
    assetPath: 'assets/road_signs_info/svg/China_road_sign_路_61c.svg',
    description:
        'https://upload.wikimedia.org/wikipedia/commons/c/c7/China_road_sign_%E8%B7%AF_61c.svg',
  ),
  TrafficSign(
    id: 'info-cn-056',
    name: 'China road sign 路 61d.svg',
    code: 'GB 5768.2-2022',
    category: SignCategory.information,
    shape: SignShape.rectangle,
    primaryColor: Color(0xFF1A5FB4),
    secondaryColor: Color(0xFFFFFFFF),
    assetPath: 'assets/road_signs_info/svg/China_road_sign_路_61d.svg',
    description:
        'https://upload.wikimedia.org/wikipedia/commons/a/a0/China_road_sign_%E8%B7%AF_61d.svg',
  ),
  TrafficSign(
    id: 'info-cn-057',
    name: 'China road sign 路 61e.svg',
    code: 'GB 5768.2-2022',
    category: SignCategory.information,
    shape: SignShape.rectangle,
    primaryColor: Color(0xFF1A5FB4),
    secondaryColor: Color(0xFFFFFFFF),
    assetPath: 'assets/road_signs_info/svg/China_road_sign_路_61e.svg',
    description:
        'https://upload.wikimedia.org/wikipedia/commons/9/94/China_road_sign_%E8%B7%AF_61e.svg',
  ),
  TrafficSign(
    id: 'info-cn-058',
    name: 'China road sign 路 62a.svg',
    code: 'GB 5768.2-2022',
    category: SignCategory.information,
    shape: SignShape.rectangle,
    primaryColor: Color(0xFF1A5FB4),
    secondaryColor: Color(0xFFFFFFFF),
    assetPath: 'assets/road_signs_info/svg/China_road_sign_路_62a.svg',
    description:
        'https://upload.wikimedia.org/wikipedia/commons/d/d5/China_road_sign_%E8%B7%AF_62a.svg',
  ),
  TrafficSign(
    id: 'info-cn-059',
    name: 'China road sign 路 62b.svg',
    code: 'GB 5768.2-2022',
    category: SignCategory.information,
    shape: SignShape.rectangle,
    primaryColor: Color(0xFF1A5FB4),
    secondaryColor: Color(0xFFFFFFFF),
    assetPath: 'assets/road_signs_info/svg/China_road_sign_路_62b.svg',
    description:
        'https://upload.wikimedia.org/wikipedia/commons/a/ae/China_road_sign_%E8%B7%AF_62b.svg',
  ),
  TrafficSign(
    id: 'info-cn-060',
    name: 'China road sign 路 65a.svg',
    code: 'GB 5768.2-2022',
    category: SignCategory.information,
    shape: SignShape.rectangle,
    primaryColor: Color(0xFF1A5FB4),
    secondaryColor: Color(0xFFFFFFFF),
    assetPath: 'assets/road_signs_info/svg/China_road_sign_路_65a.svg',
    description:
        'https://upload.wikimedia.org/wikipedia/commons/7/7c/China_road_sign_%E8%B7%AF_65a.svg',
  ),
  TrafficSign(
    id: 'info-cn-061',
    name: 'China road sign 路 65b.svg',
    code: 'GB 5768.2-2022',
    category: SignCategory.information,
    shape: SignShape.rectangle,
    primaryColor: Color(0xFF1A5FB4),
    secondaryColor: Color(0xFFFFFFFF),
    assetPath: 'assets/road_signs_info/svg/China_road_sign_路_65b.svg',
    description:
        'https://upload.wikimedia.org/wikipedia/commons/5/59/China_road_sign_%E8%B7%AF_65b.svg',
  ),
  TrafficSign(
    id: 'info-cn-062',
    name: 'China road sign 路 66a.svg',
    code: 'GB 5768.2-2022',
    category: SignCategory.information,
    shape: SignShape.rectangle,
    primaryColor: Color(0xFF1A5FB4),
    secondaryColor: Color(0xFFFFFFFF),
    assetPath: 'assets/road_signs_info/svg/China_road_sign_路_66a.svg',
    description:
        'https://upload.wikimedia.org/wikipedia/commons/8/84/China_road_sign_%E8%B7%AF_66a.svg',
  ),
  TrafficSign(
    id: 'info-cn-063',
    name: 'China road sign 路 66b.svg',
    code: 'GB 5768.2-2022',
    category: SignCategory.information,
    shape: SignShape.rectangle,
    primaryColor: Color(0xFF1A5FB4),
    secondaryColor: Color(0xFFFFFFFF),
    assetPath: 'assets/road_signs_info/svg/China_road_sign_路_66b.svg',
    description:
        'https://upload.wikimedia.org/wikipedia/commons/f/fa/China_road_sign_%E8%B7%AF_66b.svg',
  ),
  TrafficSign(
    id: 'info-cn-064',
    name: 'China road sign 路 66c.svg',
    code: 'GB 5768.2-2022',
    category: SignCategory.information,
    shape: SignShape.rectangle,
    primaryColor: Color(0xFF1A5FB4),
    secondaryColor: Color(0xFFFFFFFF),
    assetPath: 'assets/road_signs_info/svg/China_road_sign_路_66c.svg',
    description:
        'https://upload.wikimedia.org/wikipedia/commons/6/63/China_road_sign_%E8%B7%AF_66c.svg',
  ),
  TrafficSign(
    id: 'info-cn-065',
    name: 'China road sign 路 66d.svg',
    code: 'GB 5768.2-2022',
    category: SignCategory.information,
    shape: SignShape.rectangle,
    primaryColor: Color(0xFF1A5FB4),
    secondaryColor: Color(0xFFFFFFFF),
    assetPath: 'assets/road_signs_info/svg/China_road_sign_路_66d.svg',
    description:
        'https://upload.wikimedia.org/wikipedia/commons/f/f3/China_road_sign_%E8%B7%AF_66d.svg',
  ),
  TrafficSign(
    id: 'info-cn-066',
    name: 'China road sign 路 67a.svg',
    code: 'GB 5768.2-2022',
    category: SignCategory.information,
    shape: SignShape.rectangle,
    primaryColor: Color(0xFF1A5FB4),
    secondaryColor: Color(0xFFFFFFFF),
    assetPath: 'assets/road_signs_info/svg/China_road_sign_路_67a.svg',
    description:
        'https://upload.wikimedia.org/wikipedia/commons/1/17/China_road_sign_%E8%B7%AF_67a.svg',
  ),
  TrafficSign(
    id: 'info-cn-067',
    name: 'China road sign 路 67b.svg',
    code: 'GB 5768.2-2022',
    category: SignCategory.information,
    shape: SignShape.rectangle,
    primaryColor: Color(0xFF1A5FB4),
    secondaryColor: Color(0xFFFFFFFF),
    assetPath: 'assets/road_signs_info/svg/China_road_sign_路_67b.svg',
    description:
        'https://upload.wikimedia.org/wikipedia/commons/9/97/China_road_sign_%E8%B7%AF_67b.svg',
  ),
  TrafficSign(
    id: 'info-cn-068',
    name: 'China road sign 路 67c.svg',
    code: 'GB 5768.2-2022',
    category: SignCategory.information,
    shape: SignShape.rectangle,
    primaryColor: Color(0xFF1A5FB4),
    secondaryColor: Color(0xFFFFFFFF),
    assetPath: 'assets/road_signs_info/svg/China_road_sign_路_67c.svg',
    description:
        'https://upload.wikimedia.org/wikipedia/commons/1/18/China_road_sign_%E8%B7%AF_67c.svg',
  ),
  TrafficSign(
    id: 'info-cn-069',
    name: 'China road sign 路 67d.svg',
    code: 'GB 5768.2-2022',
    category: SignCategory.information,
    shape: SignShape.rectangle,
    primaryColor: Color(0xFF1A5FB4),
    secondaryColor: Color(0xFFFFFFFF),
    assetPath: 'assets/road_signs_info/svg/China_road_sign_路_67d.svg',
    description:
        'https://upload.wikimedia.org/wikipedia/commons/3/30/China_road_sign_%E8%B7%AF_67d.svg',
  ),
  TrafficSign(
    id: 'info-cn-070',
    name: 'China road sign 路 74a.svg',
    code: 'GB 5768.2-2022',
    category: SignCategory.information,
    shape: SignShape.rectangle,
    primaryColor: Color(0xFF1A5FB4),
    secondaryColor: Color(0xFFFFFFFF),
    assetPath: 'assets/road_signs_info/svg/China_road_sign_路_74a.svg',
    description:
        'https://upload.wikimedia.org/wikipedia/commons/1/1a/China_road_sign_%E8%B7%AF_74a.svg',
  ),
  TrafficSign(
    id: 'info-cn-071',
    name: 'China road sign 路 74b.svg',
    code: 'GB 5768.2-2022',
    category: SignCategory.information,
    shape: SignShape.rectangle,
    primaryColor: Color(0xFF1A5FB4),
    secondaryColor: Color(0xFFFFFFFF),
    assetPath: 'assets/road_signs_info/svg/China_road_sign_路_74b.svg',
    description:
        'https://upload.wikimedia.org/wikipedia/commons/4/4c/China_road_sign_%E8%B7%AF_74b.svg',
  ),
  TrafficSign(
    id: 'info-cn-072',
    name: 'China road sign 路 74c.svg',
    code: 'GB 5768.2-2022',
    category: SignCategory.information,
    shape: SignShape.rectangle,
    primaryColor: Color(0xFF1A5FB4),
    secondaryColor: Color(0xFFFFFFFF),
    assetPath: 'assets/road_signs_info/svg/China_road_sign_路_74c.svg',
    description:
        'https://upload.wikimedia.org/wikipedia/commons/f/f9/China_road_sign_%E8%B7%AF_74c.svg',
  ),
  TrafficSign(
    id: 'info-cn-073',
    name: 'China road sign 路 75a.svg',
    code: 'GB 5768.2-2022',
    category: SignCategory.information,
    shape: SignShape.rectangle,
    primaryColor: Color(0xFF1A5FB4),
    secondaryColor: Color(0xFFFFFFFF),
    assetPath: 'assets/road_signs_info/svg/China_road_sign_路_75a.svg',
    description:
        'https://upload.wikimedia.org/wikipedia/commons/b/b0/China_road_sign_%E8%B7%AF_75a.svg',
  ),
  TrafficSign(
    id: 'info-cn-074',
    name: 'China road sign 路 75b.svg',
    code: 'GB 5768.2-2022',
    category: SignCategory.information,
    shape: SignShape.rectangle,
    primaryColor: Color(0xFF1A5FB4),
    secondaryColor: Color(0xFFFFFFFF),
    assetPath: 'assets/road_signs_info/svg/China_road_sign_路_75b.svg',
    description:
        'https://upload.wikimedia.org/wikipedia/commons/c/cb/China_road_sign_%E8%B7%AF_75b.svg',
  ),
  TrafficSign(
    id: 'info-cn-075',
    name: 'China road sign 路 76a.svg',
    code: 'GB 5768.2-2022',
    category: SignCategory.information,
    shape: SignShape.rectangle,
    primaryColor: Color(0xFF1A5FB4),
    secondaryColor: Color(0xFFFFFFFF),
    assetPath: 'assets/road_signs_info/svg/China_road_sign_路_76a.svg',
    description:
        'https://upload.wikimedia.org/wikipedia/commons/1/1e/China_road_sign_%E8%B7%AF_76a.svg',
  ),
  TrafficSign(
    id: 'info-cn-076',
    name: 'China road sign 路 76b.svg',
    code: 'GB 5768.2-2022',
    category: SignCategory.information,
    shape: SignShape.rectangle,
    primaryColor: Color(0xFF1A5FB4),
    secondaryColor: Color(0xFFFFFFFF),
    assetPath: 'assets/road_signs_info/svg/China_road_sign_路_76b.svg',
    description:
        'https://upload.wikimedia.org/wikipedia/commons/5/5d/China_road_sign_%E8%B7%AF_76b.svg',
  ),
  TrafficSign(
    id: 'info-cn-077',
    name: 'China road sign 路 76c.svg',
    code: 'GB 5768.2-2022',
    category: SignCategory.information,
    shape: SignShape.rectangle,
    primaryColor: Color(0xFF1A5FB4),
    secondaryColor: Color(0xFFFFFFFF),
    assetPath: 'assets/road_signs_info/svg/China_road_sign_路_76c.svg',
    description:
        'https://upload.wikimedia.org/wikipedia/commons/f/f1/China_road_sign_%E8%B7%AF_76c.svg',
  ),
  TrafficSign(
    id: 'info-cn-078',
    name: 'China road sign 路 76d.svg',
    code: 'GB 5768.2-2022',
    category: SignCategory.information,
    shape: SignShape.rectangle,
    primaryColor: Color(0xFF1A5FB4),
    secondaryColor: Color(0xFFFFFFFF),
    assetPath: 'assets/road_signs_info/svg/China_road_sign_路_76d.svg',
    description:
        'https://upload.wikimedia.org/wikipedia/commons/f/f6/China_road_sign_%E8%B7%AF_76d.svg',
  ),
  TrafficSign(
    id: 'info-cn-079',
    name: 'China road sign 路 77a.svg',
    code: 'GB 5768.2-2022',
    category: SignCategory.information,
    shape: SignShape.rectangle,
    primaryColor: Color(0xFF1A5FB4),
    secondaryColor: Color(0xFFFFFFFF),
    assetPath: 'assets/road_signs_info/svg/China_road_sign_路_77a.svg',
    description:
        'https://upload.wikimedia.org/wikipedia/commons/6/6a/China_road_sign_%E8%B7%AF_77a.svg',
  ),
  TrafficSign(
    id: 'info-cn-080',
    name: 'China road sign 路 77b.svg',
    code: 'GB 5768.2-2022',
    category: SignCategory.information,
    shape: SignShape.rectangle,
    primaryColor: Color(0xFF1A5FB4),
    secondaryColor: Color(0xFFFFFFFF),
    assetPath: 'assets/road_signs_info/svg/China_road_sign_路_77b.svg',
    description:
        'https://upload.wikimedia.org/wikipedia/commons/7/7f/China_road_sign_%E8%B7%AF_77b.svg',
  ),
  TrafficSign(
    id: 'info-cn-081',
    name: 'China road sign 路 77c.svg',
    code: 'GB 5768.2-2022',
    category: SignCategory.information,
    shape: SignShape.rectangle,
    primaryColor: Color(0xFF1A5FB4),
    secondaryColor: Color(0xFFFFFFFF),
    assetPath: 'assets/road_signs_info/svg/China_road_sign_路_77c.svg',
    description:
        'https://upload.wikimedia.org/wikipedia/commons/2/27/China_road_sign_%E8%B7%AF_77c.svg',
  ),
  TrafficSign(
    id: 'info-cn-082',
    name: 'China road sign 路 77d.svg',
    code: 'GB 5768.2-2022',
    category: SignCategory.information,
    shape: SignShape.rectangle,
    primaryColor: Color(0xFF1A5FB4),
    secondaryColor: Color(0xFFFFFFFF),
    assetPath: 'assets/road_signs_info/svg/China_road_sign_路_77d.svg',
    description:
        'https://upload.wikimedia.org/wikipedia/commons/b/bd/China_road_sign_%E8%B7%AF_77d.svg',
  ),
  TrafficSign(
    id: 'info-cn-083',
    name: 'China road sign 路 79.svg',
    code: 'GB 5768.2-2022',
    category: SignCategory.information,
    shape: SignShape.rectangle,
    primaryColor: Color(0xFF1A5FB4),
    secondaryColor: Color(0xFFFFFFFF),
    assetPath: 'assets/road_signs_info/svg/China_road_sign_路_79.svg',
    description:
        'https://upload.wikimedia.org/wikipedia/commons/f/f7/China_road_sign_%E8%B7%AF_79.svg',
  ),
  TrafficSign(
    id: 'info-cn-084',
    name: 'China road sign 路 9a.svg',
    code: 'GB 5768.2-2022',
    category: SignCategory.information,
    shape: SignShape.rectangle,
    primaryColor: Color(0xFF1A5FB4),
    secondaryColor: Color(0xFFFFFFFF),
    assetPath: 'assets/road_signs_info/svg/China_road_sign_路_9a.svg',
    description:
        'https://upload.wikimedia.org/wikipedia/commons/2/2a/China_road_sign_%E8%B7%AF_9a.svg',
  ),
  TrafficSign(
    id: 'info-cn-085',
    name: 'China road sign 路 9b.svg',
    code: 'GB 5768.2-2022',
    category: SignCategory.information,
    shape: SignShape.rectangle,
    primaryColor: Color(0xFF1A5FB4),
    secondaryColor: Color(0xFFFFFFFF),
    assetPath: 'assets/road_signs_info/svg/China_road_sign_路_9b.svg',
    description:
        'https://upload.wikimedia.org/wikipedia/commons/e/ef/China_road_sign_%E8%B7%AF_9b.svg',
  ),
];
