import 'package:flutter/material.dart';
import '../models/traffic_sign.dart';

class Gb5768Colors {
  static const Color red = Color(0xFFE60000);
  static const Color blue = Color(0xFF0066CC);
  static const Color yellow = Color(0xFFFFD100);
  static const Color green = Color(0xFF007A33);
  static const Color white = Color(0xFFFFFFFF);
  static const Color black = Color(0xFF000000);
  static const Color brown = Color(0xFF8B4513);
  static const Color orange = Color(0xFFFF6600);
  static const Color gray = Color(0xFF808080);
}

class Gb5768Signs {
  static List<TrafficSign> get allSigns => [
        ...prohibitionSigns,
        ...warningSigns,
        ...mandatorySigns,
        ...indicationSigns,
        ...informationSigns,
      ];

  static List<TrafficSign> get prohibitionSigns => [
        TrafficSign(
          id: 'pr001',
          name: '禁止通行',
          code: 'GB 5768.2-2022',
          category: SignCategory.prohibition,
          shape: SignShape.circle,
          primaryColor: Gb5768Colors.red,
          description: '禁止一切车辆和行人通行',
        ),
        TrafficSign(
          id: 'pr002',
          name: '禁止驶入',
          code: 'GB 5768.2-2022',
          category: SignCategory.prohibition,
          shape: SignShape.circle,
          primaryColor: Gb5768Colors.red,
          description: '禁止车辆驶入',
        ),
        TrafficSign(
          id: 'pr003',
          name: '禁止机动车通行',
          code: 'GB 5768.2-2022',
          category: SignCategory.prohibition,
          shape: SignShape.circle,
          primaryColor: Gb5768Colors.red,
          description: '禁止机动车通行',
        ),
        TrafficSign(
          id: 'pr004',
          name: '禁止载货汽车通行',
          code: 'GB 5768.2-2022',
          category: SignCategory.prohibition,
          shape: SignShape.circle,
          primaryColor: Gb5768Colors.red,
          description: '禁止载货汽车通行',
        ),
        TrafficSign(
          id: 'pr005',
          name: '禁止电动自行车通行',
          code: 'GB 5768.2-2022',
          category: SignCategory.prohibition,
          shape: SignShape.circle,
          primaryColor: Gb5768Colors.red,
          description: '禁止电动自行车通行',
        ),
        TrafficSign(
          id: 'pr006',
          name: '禁止人力车通行',
          code: 'GB 5768.2-2022',
          category: SignCategory.prohibition,
          shape: SignShape.circle,
          primaryColor: Gb5768Colors.red,
          description: '禁止人力车通行',
        ),
        TrafficSign(
          id: 'pr007',
          name: '禁止行人通行',
          code: 'GB 5768.2-2022',
          category: SignCategory.prohibition,
          shape: SignShape.circle,
          primaryColor: Gb5768Colors.red,
          description: '禁止行人通行',
        ),
        TrafficSign(
          id: 'pr008',
          name: '禁止向左转弯',
          code: 'GB 5768.2-2022',
          category: SignCategory.prohibition,
          shape: SignShape.circle,
          primaryColor: Gb5768Colors.red,
          description: '禁止车辆向左转弯',
        ),
        TrafficSign(
          id: 'pr009',
          name: '禁止向右转弯',
          code: 'GB 5768.2-2022',
          category: SignCategory.prohibition,
          shape: SignShape.circle,
          primaryColor: Gb5768Colors.red,
          description: '禁止车辆向右转弯',
        ),
        TrafficSign(
          id: 'pr010',
          name: '禁止直行',
          code: 'GB 5768.2-2022',
          category: SignCategory.prohibition,
          shape: SignShape.circle,
          primaryColor: Gb5768Colors.red,
          description: '禁止车辆直行',
        ),
        TrafficSign(
          id: 'pr011',
          name: '禁止掉头',
          code: 'GB 5768.2-2022',
          category: SignCategory.prohibition,
          shape: SignShape.circle,
          primaryColor: Gb5768Colors.red,
          description: '禁止车辆掉头',
        ),
        TrafficSign(
          id: 'pr012',
          name: '禁止超车',
          code: 'GB 5768.2-2022',
          category: SignCategory.prohibition,
          shape: SignShape.circle,
          primaryColor: Gb5768Colors.red,
          description: '禁止超车',
        ),
        TrafficSign(
          id: 'pr013',
          name: '解除禁止超车',
          code: 'GB 5768.2-2022',
          category: SignCategory.prohibition,
          shape: SignShape.circle,
          primaryColor: Gb5768Colors.black,
          description: '解除禁止超车',
        ),
        TrafficSign(
          id: 'pr014',
          name: '限制速度',
          code: 'GB 5768.2-2022',
          category: SignCategory.prohibition,
          shape: SignShape.circle,
          primaryColor: Gb5768Colors.red,
          description: '限制车辆速度',
        ),
        TrafficSign(
          id: 'pr015',
          name: '解除限制速度',
          code: 'GB 5768.2-2022',
          category: SignCategory.prohibition,
          shape: SignShape.circle,
          primaryColor: Gb5768Colors.black,
          description: '解除限制速度',
        ),
        TrafficSign(
          id: 'pr016',
          name: '停车检查',
          code: 'GB 5768.2-2022',
          category: SignCategory.prohibition,
          shape: SignShape.circle,
          primaryColor: Gb5768Colors.red,
          description: '停车接受检查',
        ),
        TrafficSign(
          id: 'pr017',
          name: '停车让行',
          code: 'GB 5768.2-2022',
          category: SignCategory.prohibition,
          shape: SignShape.invertedTriangle,
          primaryColor: Gb5768Colors.red,
          description: '停车让行',
        ),
        TrafficSign(
          id: 'pr018',
          name: '减速让行',
          code: 'GB 5768.2-2022',
          category: SignCategory.prohibition,
          shape: SignShape.invertedTriangle,
          primaryColor: Gb5768Colors.red,
          description: '减速让行',
        ),
        TrafficSign(
          id: 'pr019',
          name: '禁止鸣喇叭',
          code: 'GB 5768.2-2022',
          category: SignCategory.prohibition,
          shape: SignShape.circle,
          primaryColor: Gb5768Colors.red,
          description: '禁止鸣喇叭',
        ),
        TrafficSign(
          id: 'pr020',
          name: '会车让行',
          code: 'GB 5768.2-2022',
          category: SignCategory.prohibition,
          shape: SignShape.circle,
          primaryColor: Gb5768Colors.red,
          description: '会车时让对方先行',
        ),
      ];

  static List<TrafficSign> get warningSigns => [
        TrafficSign(
          id: 'wr001',
          name: '十字交叉',
          code: 'GB 5768.2-2022',
          category: SignCategory.warning,
          shape: SignShape.invertedTriangle,
          primaryColor: Gb5768Colors.yellow,
          description: '前方十字交叉路口',
        ),
        TrafficSign(
          id: 'wr002',
          name: 'T形交叉',
          code: 'GB 5768.2-2022',
          category: SignCategory.warning,
          shape: SignShape.invertedTriangle,
          primaryColor: Gb5768Colors.yellow,
          description: '前方T形交叉路口',
        ),
        TrafficSign(
          id: 'wr003',
          name: 'T形交叉左侧',
          code: 'GB 5768.2-2022',
          category: SignCategory.warning,
          shape: SignShape.invertedTriangle,
          primaryColor: Gb5768Colors.yellow,
          description: '前方T形交叉路口(左侧)',
        ),
        TrafficSign(
          id: 'wr004',
          name: 'Y形交叉',
          code: 'GB 5768.2-2022',
          category: SignCategory.warning,
          shape: SignShape.invertedTriangle,
          primaryColor: Gb5768Colors.yellow,
          description: '前方Y形交叉路口',
        ),
        TrafficSign(
          id: 'wr005',
          name: '环形交叉',
          code: 'GB 5768.2-2022',
          category: SignCategory.warning,
          shape: SignShape.invertedTriangle,
          primaryColor: Gb5768Colors.yellow,
          description: '前方环形交叉路口',
        ),
        TrafficSign(
          id: 'wr006',
          name: '急弯路',
          code: 'GB 5768.2-2022',
          category: SignCategory.warning,
          shape: SignShape.invertedTriangle,
          primaryColor: Gb5768Colors.yellow,
          description: '前方急弯路',
        ),
        TrafficSign(
          id: 'wr007',
          name: '反向弯路',
          code: 'GB 5768.2-2022',
          category: SignCategory.warning,
          shape: SignShape.invertedTriangle,
          primaryColor: Gb5768Colors.yellow,
          description: '前方反向弯路',
        ),
        TrafficSign(
          id: 'wr008',
          name: '连续弯路',
          code: 'GB 5768.2-2022',
          category: SignCategory.warning,
          shape: SignShape.invertedTriangle,
          primaryColor: Gb5768Colors.yellow,
          description: '前方连续弯路',
        ),
        TrafficSign(
          id: 'wr009',
          name: '上坡路',
          code: 'GB 5768.2-2022',
          category: SignCategory.warning,
          shape: SignShape.invertedTriangle,
          primaryColor: Gb5768Colors.yellow,
          description: '上坡',
        ),
        TrafficSign(
          id: 'wr010',
          name: '下坡路',
          code: 'GB 5768.2-2022',
          category: SignCategory.warning,
          shape: SignShape.invertedTriangle,
          primaryColor: Gb5768Colors.yellow,
          description: '下坡',
        ),
        TrafficSign(
          id: 'wr011',
          name: '两侧变窄',
          code: 'GB 5768.2-2022',
          category: SignCategory.warning,
          shape: SignShape.invertedTriangle,
          primaryColor: Gb5768Colors.yellow,
          description: '道路两侧变窄',
        ),
        TrafficSign(
          id: 'wr012',
          name: '左侧变窄',
          code: 'GB 5768.2-2022',
          category: SignCategory.warning,
          shape: SignShape.invertedTriangle,
          primaryColor: Gb5768Colors.yellow,
          description: '道路左侧变窄',
        ),
        TrafficSign(
          id: 'wr013',
          name: '右侧变窄',
          code: 'GB 5768.2-2022',
          category: SignCategory.warning,
          shape: SignShape.invertedTriangle,
          primaryColor: Gb5768Colors.yellow,
          description: '道路右侧变窄',
        ),
        TrafficSign(
          id: 'wr014',
          name: '窄桥',
          code: 'GB 5768.2-2022',
          category: SignCategory.warning,
          shape: SignShape.invertedTriangle,
          primaryColor: Gb5768Colors.yellow,
          description: '窄桥',
        ),
        TrafficSign(
          id: 'wr015',
          name: '双向交通',
          code: 'GB 5768.2-2022',
          category: SignCategory.warning,
          shape: SignShape.invertedTriangle,
          primaryColor: Gb5768Colors.yellow,
          description: '双向交通',
        ),
        TrafficSign(
          id: 'wr016',
          name: '注意行人',
          code: 'GB 5768.2-2022',
          category: SignCategory.warning,
          shape: SignShape.invertedTriangle,
          primaryColor: Gb5768Colors.yellow,
          description: '注意行人',
        ),
        TrafficSign(
          id: 'wr017',
          name: '注意儿童',
          code: 'GB 5768.2-2022',
          category: SignCategory.warning,
          shape: SignShape.invertedTriangle,
          primaryColor: Gb5768Colors.yellow,
          description: '注意儿童',
        ),
        TrafficSign(
          id: 'wr018',
          name: '注意非机动车',
          code: 'GB 5768.2-2022',
          category: SignCategory.warning,
          shape: SignShape.invertedTriangle,
          primaryColor: Gb5768Colors.yellow,
          description: '注意非机动车',
        ),
        TrafficSign(
          id: 'wr019',
          name: '注意信号灯',
          code: 'GB 5768.2-2022',
          category: SignCategory.warning,
          shape: SignShape.invertedTriangle,
          primaryColor: Gb5768Colors.yellow,
          description: '注意信号灯',
        ),
        TrafficSign(
          id: 'wr020',
          name: '注意障碍物',
          code: 'GB 5768.2-2022',
          category: SignCategory.warning,
          shape: SignShape.invertedTriangle,
          primaryColor: Gb5768Colors.yellow,
          description: '注意障碍物',
        ),
        TrafficSign(
          id: 'wr021',
          name: '注意危险',
          code: 'GB 5768.2-2022',
          category: SignCategory.warning,
          shape: SignShape.invertedTriangle,
          primaryColor: Gb5768Colors.yellow,
          description: '注意危险',
        ),
        TrafficSign(
          id: 'wr022',
          name: '施工',
          code: 'GB 5768.2-2022',
          category: SignCategory.warning,
          shape: SignShape.invertedTriangle,
          primaryColor: Gb5768Colors.orange,
          description: '道路施工',
        ),
        TrafficSign(
          id: 'wr023',
          name: '建议速度',
          code: 'GB 5768.2-2022',
          category: SignCategory.warning,
          shape: SignShape.invertedTriangle,
          primaryColor: Gb5768Colors.yellow,
          description: '建议速度',
        ),
        TrafficSign(
          id: 'wr024',
          name: '路面高凸',
          code: 'GB 5768.2-2022',
          category: SignCategory.warning,
          shape: SignShape.invertedTriangle,
          primaryColor: Gb5768Colors.yellow,
          description: '路面高凸',
        ),
        TrafficSign(
          id: 'wr025',
          name: '路面低洼',
          code: 'GB 5768.2-2022',
          category: SignCategory.warning,
          shape: SignShape.invertedTriangle,
          primaryColor: Gb5768Colors.yellow,
          description: '路面低洼',
        ),
        TrafficSign(
          id: 'wr026',
          name: '小心滑溜',
          code: 'GB 5768.2-2022',
          category: SignCategory.warning,
          shape: SignShape.invertedTriangle,
          primaryColor: Gb5768Colors.yellow,
          description: '湿滑路面',
        ),
        TrafficSign(
          id: 'wr027',
          name: '有人看守铁路道口',
          code: 'GB 5768.2-2022',
          category: SignCategory.warning,
          shape: SignShape.invertedTriangle,
          primaryColor: Gb5768Colors.yellow,
          description: '有人看守铁路道口',
        ),
        TrafficSign(
          id: 'wr028',
          name: '无人看守铁路道口',
          code: 'GB 5768.2-2022',
          category: SignCategory.warning,
          shape: SignShape.invertedTriangle,
          primaryColor: Gb5768Colors.yellow,
          description: '无人看守铁路道口',
        ),
        TrafficSign(
          id: 'wr029',
          name: '注意落石',
          code: 'GB 5768.2-2022',
          category: SignCategory.warning,
          shape: SignShape.invertedTriangle,
          primaryColor: Gb5768Colors.yellow,
          description: '注意落石',
        ),
        TrafficSign(
          id: 'wr030',
          name: '傍山险路',
          code: 'GB 5768.2-2022',
          category: SignCategory.warning,
          shape: SignShape.invertedTriangle,
          primaryColor: Gb5768Colors.yellow,
          description: '傍山险路',
        ),
        TrafficSign(
          id: 'wr031',
          name: '堤坝路',
          code: 'GB 5768.2-2022',
          category: SignCategory.warning,
          shape: SignShape.invertedTriangle,
          primaryColor: Gb5768Colors.yellow,
          description: '堤坝路',
        ),
        TrafficSign(
          id: 'wr032',
          name: '村庄',
          code: 'GB 5768.2-2022',
          category: SignCategory.warning,
          shape: SignShape.invertedTriangle,
          primaryColor: Gb5768Colors.yellow,
          description: '村庄',
        ),
        TrafficSign(
          id: 'wr033',
          name: '注意牲畜',
          code: 'GB 5768.2-2022',
          category: SignCategory.warning,
          shape: SignShape.invertedTriangle,
          primaryColor: Gb5768Colors.yellow,
          description: '注意牲畜',
        ),
        TrafficSign(
          id: 'wr034',
          name: '注意野生动物',
          code: 'GB 5768.2-2022',
          category: SignCategory.warning,
          shape: SignShape.invertedTriangle,
          primaryColor: Gb5768Colors.yellow,
          description: '注意野生动物',
        ),
        TrafficSign(
          id: 'wr035',
          name: '事故易发路段',
          code: 'GB 5768.2-2022',
          category: SignCategory.warning,
          shape: SignShape.invertedTriangle,
          primaryColor: Gb5768Colors.yellow,
          description: '事故易发路段',
        ),
        TrafficSign(
          id: 'wr036',
          name: '慢行',
          code: 'GB 5768.2-2022',
          category: SignCategory.warning,
          shape: SignShape.invertedTriangle,
          primaryColor: Gb5768Colors.yellow,
          description: '慢行',
        ),
        TrafficSign(
          id: 'wr037',
          name: '避险车道',
          code: 'GB 5768.2-2022',
          category: SignCategory.warning,
          shape: SignShape.invertedTriangle,
          primaryColor: Gb5768Colors.yellow,
          description: '避险车道',
        ),
        TrafficSign(
          id: 'wr038',
          name: '注意潮汐车道',
          code: 'GB 5768.2-2022',
          category: SignCategory.warning,
          shape: SignShape.invertedTriangle,
          primaryColor: Gb5768Colors.yellow,
          description: '注意潮汐车道',
        ),
      ];

  static List<TrafficSign> get mandatorySigns => [
        TrafficSign(
          id: 'md001',
          name: '直行',
          code: 'GB 5768.2-2022',
          category: SignCategory.mandatory,
          shape: SignShape.circle,
          primaryColor: Gb5768Colors.blue,
          description: '只准直行',
        ),
        TrafficSign(
          id: 'md002',
          name: '向左转弯',
          code: 'GB 5768.2-2022',
          category: SignCategory.mandatory,
          shape: SignShape.circle,
          primaryColor: Gb5768Colors.blue,
          description: '只准向左转弯',
        ),
        TrafficSign(
          id: 'md003',
          name: '向右转弯',
          code: 'GB 5768.2-2022',
          category: SignCategory.mandatory,
          shape: SignShape.circle,
          primaryColor: Gb5768Colors.blue,
          description: '只准向右转弯',
        ),
        TrafficSign(
          id: 'md004',
          name: '直行和向左转弯',
          code: 'GB 5768.2-2022',
          category: SignCategory.mandatory,
          shape: SignShape.circle,
          primaryColor: Gb5768Colors.blue,
          description: '准许直行和向左转弯',
        ),
        TrafficSign(
          id: 'md005',
          name: '直行和向右转弯',
          code: 'GB 5768.2-2022',
          category: SignCategory.mandatory,
          shape: SignShape.circle,
          primaryColor: Gb5768Colors.blue,
          description: '准许直行和向右转弯',
        ),
        TrafficSign(
          id: 'md006',
          name: '向左和向右转弯',
          code: 'GB 5768.2-2022',
          category: SignCategory.mandatory,
          shape: SignShape.circle,
          primaryColor: Gb5768Colors.blue,
          description: '准许向左和向右转弯',
        ),
        TrafficSign(
          id: 'md007',
          name: '靠右侧道路行驶',
          code: 'GB 5768.2-2022',
          category: SignCategory.mandatory,
          shape: SignShape.circle,
          primaryColor: Gb5768Colors.blue,
          description: '靠右侧道路行驶',
        ),
        TrafficSign(
          id: 'md008',
          name: '靠左侧道路行驶',
          code: 'GB 5768.2-2022',
          category: SignCategory.mandatory,
          shape: SignShape.circle,
          primaryColor: Gb5768Colors.blue,
          description: '靠左侧道路行驶',
        ),
        TrafficSign(
          id: 'md009',
          name: '环岛行驶',
          code: 'GB 5768.2-2022',
          category: SignCategory.mandatory,
          shape: SignShape.circle,
          primaryColor: Gb5768Colors.blue,
          description: '环岛行驶',
        ),
        TrafficSign(
          id: 'md010',
          name: '单行路',
          code: 'GB 5768.2-2022',
          category: SignCategory.mandatory,
          shape: SignShape.rectangle,
          primaryColor: Gb5768Colors.blue,
          description: '单行路',
        ),
        TrafficSign(
          id: 'md011',
          name: '最低限速',
          code: 'GB 5768.2-2022',
          category: SignCategory.mandatory,
          shape: SignShape.circle,
          primaryColor: Gb5768Colors.blue,
          description: '最低限速',
        ),
        TrafficSign(
          id: 'md012',
          name: '最高限速',
          code: 'GB 5768.2-2022',
          category: SignCategory.mandatory,
          shape: SignShape.rectangle,
          primaryColor: Gb5768Colors.blue,
          description: '最高限速',
        ),
        TrafficSign(
          id: 'md013',
          name: '干路先行',
          code: 'GB 5768.2-2022',
          category: SignCategory.mandatory,
          shape: SignShape.rectangle,
          primaryColor: Gb5768Colors.blue,
          description: '干路先行',
        ),
        TrafficSign(
          id: 'md014',
          name: '会车先行',
          code: 'GB 5768.2-2022',
          category: SignCategory.mandatory,
          shape: SignShape.rectangle,
          primaryColor: Gb5768Colors.blue,
          description: '会车先行',
        ),
        TrafficSign(
          id: 'md015',
          name: '鸣喇叭',
          code: 'GB 5768.2-2022',
          category: SignCategory.mandatory,
          shape: SignShape.circle,
          primaryColor: Gb5768Colors.blue,
          description: '鸣喇叭',
        ),
        TrafficSign(
          id: 'md016',
          name: '掉头',
          code: 'GB 5768.2-2022',
          category: SignCategory.mandatory,
          shape: SignShape.circle,
          primaryColor: Gb5768Colors.blue,
          description: '准许掉头',
        ),
      ];

  static List<TrafficSign> get indicationSigns => [
        TrafficSign(
          id: 'in001',
          name: '路口通行',
          code: 'GB 5768.2-2022',
          category: SignCategory.indication,
          shape: SignShape.rectangle,
          primaryColor: Gb5768Colors.green,
          description: '路口通行',
        ),
        TrafficSign(
          id: 'in002',
          name: '四行车道变为三车道',
          code: 'GB 5768.2-2022',
          category: SignCategory.indication,
          shape: SignShape.rectangle,
          primaryColor: Gb5768Colors.green,
          description: '四行车道变为三车道',
        ),
        TrafficSign(
          id: 'in003',
          name: '四行车道变为二车道',
          code: 'GB 5768.2-2022',
          category: SignCategory.indication,
          shape: SignShape.rectangle,
          primaryColor: Gb5768Colors.green,
          description: '四行车道变为二车道',
        ),
        TrafficSign(
          id: 'in004',
          name: '三行车道变为二车道',
          code: 'GB 5768.2-2022',
          category: SignCategory.indication,
          shape: SignShape.rectangle,
          primaryColor: Gb5768Colors.green,
          description: '三行车道变为二车道',
        ),
        TrafficSign(
          id: 'in005',
          name: '二行车道变为三车道',
          code: 'GB 5768.2-2022',
          category: SignCategory.indication,
          shape: SignShape.rectangle,
          primaryColor: Gb5768Colors.green,
          description: '二行车道变为三车道',
        ),
        TrafficSign(
          id: 'in006',
          name: '二行车道变为四车道',
          code: 'GB 5768.2-2022',
          category: SignCategory.indication,
          shape: SignShape.rectangle,
          primaryColor: Gb5768Colors.green,
          description: '二行车道变为四车道',
        ),
        TrafficSign(
          id: 'in007',
          name: '三行车道变为四车道',
          code: 'GB 5768.2-2022',
          category: SignCategory.indication,
          shape: SignShape.rectangle,
          primaryColor: Gb5768Colors.green,
          description: '三行车道变为四车道',
        ),
        TrafficSign(
          id: 'in008',
          name: '大交通量三车道变为二车道',
          code: 'GB 5768.2-2022',
          category: SignCategory.indication,
          shape: SignShape.rectangle,
          primaryColor: Gb5768Colors.green,
          description: '大交通量三车道变为二车道',
        ),
        TrafficSign(
          id: 'in009',
          name: '交通转换',
          code: 'GB 5768.2-2022',
          category: SignCategory.indication,
          shape: SignShape.rectangle,
          primaryColor: Gb5768Colors.green,
          description: '交通转换',
        ),
        TrafficSign(
          id: 'in010',
          name: '非机动车行驶',
          code: 'GB 5768.2-2022',
          category: SignCategory.indication,
          shape: SignShape.rectangle,
          primaryColor: Gb5768Colors.blue,
          description: '非机动车行驶',
        ),
        TrafficSign(
          id: 'in011',
          name: '非机动车推行',
          code: 'GB 5768.2-2022',
          category: SignCategory.indication,
          shape: SignShape.rectangle,
          primaryColor: Gb5768Colors.blue,
          description: '非机动车推行',
        ),
        TrafficSign(
          id: 'in012',
          name: '分向行驶',
          code: 'GB 5768.2-2022',
          category: SignCategory.indication,
          shape: SignShape.rectangle,
          primaryColor: Gb5768Colors.green,
          description: '分向行驶',
        ),
        TrafficSign(
          id: 'in013',
          name: '行人专用',
          code: 'GB 5768.2-2022',
          category: SignCategory.indication,
          shape: SignShape.rectangle,
          primaryColor: Gb5768Colors.blue,
          description: '行人专用',
        ),
        TrafficSign(
          id: 'in014',
          name: '机动车行驶',
          code: 'GB 5768.2-2022',
          category: SignCategory.indication,
          shape: SignShape.rectangle,
          primaryColor: Gb5768Colors.green,
          description: '机动车行驶',
        ),
      ];

  static List<TrafficSign> get informationSigns => [
        TrafficSign(
          id: 'if001',
          name: '入口预告',
          code: 'GB 5768.2-2022',
          category: SignCategory.information,
          shape: SignShape.rectangle,
          primaryColor: Gb5768Colors.green,
          description: '入口预告',
        ),
        TrafficSign(
          id: 'if002',
          name: '出口预告',
          code: 'GB 5768.2-2022',
          category: SignCategory.information,
          shape: SignShape.rectangle,
          primaryColor: Gb5768Colors.green,
          description: '出口预告',
        ),
        TrafficSign(
          id: 'if003',
          name: '地点方向',
          code: 'GB 5768.2-2022',
          category: SignCategory.information,
          shape: SignShape.rectangle,
          primaryColor: Gb5768Colors.green,
          description: '地点方向',
        ),
        TrafficSign(
          id: 'if004',
          name: '地点距离',
          code: 'GB 5768.2-2022',
          category: SignCategory.information,
          shape: SignShape.rectangle,
          primaryColor: Gb5768Colors.green,
          description: '地点距离',
        ),
        TrafficSign(
          id: 'if005',
          name: '命名编号',
          code: 'GB 5768.2-2022',
          category: SignCategory.information,
          shape: SignShape.rectangle,
          primaryColor: Gb5768Colors.green,
          description: '命名编号',
        ),
        TrafficSign(
          id: 'if006',
          name: '停车区',
          code: 'GB 5768.2-2022',
          category: SignCategory.information,
          shape: SignShape.rectangle,
          primaryColor: Gb5768Colors.blue,
          description: '停车区',
        ),
        TrafficSign(
          id: 'if007',
          name: '服务区',
          code: 'GB 5768.2-2022',
          category: SignCategory.information,
          shape: SignShape.rectangle,
          primaryColor: Gb5768Colors.blue,
          description: '服务区',
        ),
        TrafficSign(
          id: 'if008',
          name: '加油站',
          code: 'GB 5768.2-2022',
          category: SignCategory.information,
          shape: SignShape.rectangle,
          primaryColor: Gb5768Colors.blue,
          description: '加油站',
        ),
        TrafficSign(
          id: 'if009',
          name: '紧急停车带',
          code: 'GB 5768.2-2022',
          category: SignCategory.information,
          shape: SignShape.rectangle,
          primaryColor: Gb5768Colors.blue,
          description: '紧急停车带',
        ),
        TrafficSign(
          id: 'if010',
          name: '爬坡车道',
          code: 'GB 5768.2-2022',
          category: SignCategory.information,
          shape: SignShape.rectangle,
          primaryColor: Gb5768Colors.green,
          description: '爬坡车道',
        ),
        TrafficSign(
          id: 'if011',
          name: '车距确认',
          code: 'GB 5768.2-2022',
          category: SignCategory.information,
          shape: SignShape.rectangle,
          primaryColor: Gb5768Colors.green,
          description: '车距确认',
        ),
        TrafficSign(
          id: 'if012',
          name: '里程牌',
          code: 'GB 5768.2-2022',
          category: SignCategory.information,
          shape: SignShape.rectangle,
          primaryColor: Gb5768Colors.green,
          description: '里程牌',
        ),
        TrafficSign(
          id: 'if013',
          name: '百米牌',
          code: 'GB 5768.2-2022',
          category: SignCategory.information,
          shape: SignShape.square,
          primaryColor: Gb5768Colors.green,
          description: '百米牌',
        ),
        TrafficSign(
          id: 'if014',
          name: '分流、合流',
          code: 'GB 5768.2-2022',
          category: SignCategory.information,
          shape: SignShape.rectangle,
          primaryColor: Gb5768Colors.green,
          description: '分流、合流',
        ),
        TrafficSign(
          id: 'if015',
          name: '线形诱导标',
          code: 'GB 5768.2-2022',
          category: SignCategory.information,
          shape: SignShape.rectangle,
          primaryColor: Gb5768Colors.blue,
          description: '线形诱导标',
        ),
      ];

  static List<TrafficSign> getByCategory(SignCategory category) {
    switch (category) {
      case SignCategory.prohibition:
        return prohibitionSigns;
      case SignCategory.warning:
        return warningSigns;
      case SignCategory.mandatory:
        return mandatorySigns;
      case SignCategory.indication:
        return indicationSigns;
      case SignCategory.information:
        return informationSigns;
      case SignCategory.auxiliary:
        return [];
    }
  }
}
