import 'package:flutter/material.dart';

import '../models/traffic_sign.dart';
import 'china_information_signs.dart';

class Gb5768Colors {
  static const Color red = Color(0xFFD92323);
  static const Color blue = Color(0xFF1A5FB4);
  static const Color yellow = Color(0xFFFFC72C);
  static const Color green = Color(0xFF0E8A4B);
  static const Color brown = Color(0xFF8C5A2B);
  static const Color white = Color(0xFFFFFFFF);
  static const Color black = Color(0xFF111111);
}

class Gb5768Signs {
  static const String code = 'GB 5768.2-2022';
  static const String _assetBase = 'assets/road_signs';

  static List<TrafficSign> get allSigns => [
    ...prohibitionSigns,
    ...warningSigns,
    ...mandatorySigns,
    ...indicationSigns,
    ...informationSigns,
  ];

  static List<TrafficSign> get prohibitionSigns => const [
    TrafficSign(
      id: 'pro-stop',
      name: '停车让行',
      code: code,
      category: SignCategory.prohibition,
      shape: SignShape.octagon,
      primaryColor: Gb5768Colors.red,
      secondaryColor: Gb5768Colors.white,
      assetPath: '$_assetBase/stop.svg',
      symbol: SignSymbol.stopText,
    ),
    TrafficSign(
      id: 'pro-yield',
      name: '减速让行',
      code: code,
      category: SignCategory.prohibition,
      shape: SignShape.invertedTriangle,
      primaryColor: Gb5768Colors.white,
      secondaryColor: Gb5768Colors.red,
      borderColor: Gb5768Colors.red,
      assetPath: '$_assetBase/yield.svg',
      symbol: SignSymbol.yieldText,
    ),
    TrafficSign(
      id: 'pro-give-way-oncoming',
      name: '会车让行',
      code: code,
      category: SignCategory.prohibition,
      shape: SignShape.circle,
      primaryColor: Gb5768Colors.white,
      secondaryColor: Gb5768Colors.black,
      borderColor: Gb5768Colors.red,
      assetPath: '$_assetBase/give_way_oncoming.svg',
    ),
    TrafficSign(
      id: 'pro-no-entry',
      name: '禁止驶入',
      code: code,
      category: SignCategory.prohibition,
      shape: SignShape.circle,
      primaryColor: Gb5768Colors.red,
      secondaryColor: Gb5768Colors.white,
      assetPath: '$_assetBase/no_entry.svg',
      symbol: SignSymbol.noEntry,
    ),
    TrafficSign(
      id: 'pro-no-through',
      name: '禁止通行',
      code: code,
      category: SignCategory.prohibition,
      shape: SignShape.circle,
      primaryColor: Gb5768Colors.white,
      secondaryColor: Gb5768Colors.red,
      borderColor: Gb5768Colors.red,
      assetPath: '$_assetBase/no_through.svg',
    ),
    TrafficSign(
      id: 'pro-no-motor-vehicles',
      name: '禁止机动车驶入',
      code: code,
      category: SignCategory.prohibition,
      shape: SignShape.circle,
      primaryColor: Gb5768Colors.white,
      secondaryColor: Gb5768Colors.black,
      borderColor: Gb5768Colors.red,
      assetPath: '$_assetBase/no_motor_vehicles.svg',
      symbol: SignSymbol.noMotorVehicles,
    ),
    TrafficSign(
      id: 'pro-no-trucks',
      name: '禁止载货汽车驶入',
      code: code,
      category: SignCategory.prohibition,
      shape: SignShape.circle,
      primaryColor: Gb5768Colors.white,
      secondaryColor: Gb5768Colors.black,
      borderColor: Gb5768Colors.red,
      assetPath: '$_assetBase/no_trucks.svg',
    ),
    TrafficSign(
      id: 'pro-no-motorcycles',
      name: '禁止摩托车驶入',
      code: code,
      category: SignCategory.prohibition,
      shape: SignShape.circle,
      primaryColor: Gb5768Colors.white,
      secondaryColor: Gb5768Colors.black,
      borderColor: Gb5768Colors.red,
      assetPath: '$_assetBase/no_motorcycles.svg',
    ),
    TrafficSign(
      id: 'pro-no-pedestrians',
      name: '禁止行人进入',
      code: code,
      category: SignCategory.prohibition,
      shape: SignShape.circle,
      primaryColor: Gb5768Colors.white,
      secondaryColor: Gb5768Colors.black,
      borderColor: Gb5768Colors.red,
      assetPath: '$_assetBase/no_pedestrians.svg',
      symbol: SignSymbol.noPedestrians,
    ),
    TrafficSign(
      id: 'pro-no-two-vehicle-types',
      name: '禁止某两种车驶入',
      code: code,
      category: SignCategory.prohibition,
      shape: SignShape.circle,
      primaryColor: Gb5768Colors.white,
      secondaryColor: Gb5768Colors.black,
      borderColor: Gb5768Colors.red,
      assetPath: '$_assetBase/no_two_vehicle_types.svg',
    ),
    TrafficSign(
      id: 'pro-no-left-turn',
      name: '禁止向左转弯',
      code: code,
      category: SignCategory.prohibition,
      shape: SignShape.circle,
      primaryColor: Gb5768Colors.white,
      secondaryColor: Gb5768Colors.black,
      borderColor: Gb5768Colors.red,
      assetPath: '$_assetBase/no_left_turn.svg',
    ),
    TrafficSign(
      id: 'pro-no-right-turn',
      name: '禁止向右转弯',
      code: code,
      category: SignCategory.prohibition,
      shape: SignShape.circle,
      primaryColor: Gb5768Colors.white,
      secondaryColor: Gb5768Colors.black,
      borderColor: Gb5768Colors.red,
      assetPath: '$_assetBase/no_right_turn.svg',
    ),
    TrafficSign(
      id: 'pro-no-straight',
      name: '禁止直行',
      code: code,
      category: SignCategory.prohibition,
      shape: SignShape.circle,
      primaryColor: Gb5768Colors.white,
      secondaryColor: Gb5768Colors.black,
      borderColor: Gb5768Colors.red,
      assetPath: '$_assetBase/no_straight.svg',
    ),
    TrafficSign(
      id: 'pro-no-left-right-turn',
      name: '禁止向左向右转弯',
      code: code,
      category: SignCategory.prohibition,
      shape: SignShape.circle,
      primaryColor: Gb5768Colors.white,
      secondaryColor: Gb5768Colors.black,
      borderColor: Gb5768Colors.red,
      assetPath: '$_assetBase/no_left_right_turn.svg',
    ),
    TrafficSign(
      id: 'pro-no-straight-left',
      name: '禁止直行和向左转弯',
      code: code,
      category: SignCategory.prohibition,
      shape: SignShape.circle,
      primaryColor: Gb5768Colors.white,
      secondaryColor: Gb5768Colors.black,
      borderColor: Gb5768Colors.red,
      assetPath: '$_assetBase/no_straight_left.svg',
    ),
    TrafficSign(
      id: 'pro-no-straight-right',
      name: '禁止直行和向右转弯',
      code: code,
      category: SignCategory.prohibition,
      shape: SignShape.circle,
      primaryColor: Gb5768Colors.white,
      secondaryColor: Gb5768Colors.black,
      borderColor: Gb5768Colors.red,
      assetPath: '$_assetBase/no_straight_right.svg',
    ),
    TrafficSign(
      id: 'pro-no-uturn',
      name: '禁止掉头',
      code: code,
      category: SignCategory.prohibition,
      shape: SignShape.circle,
      primaryColor: Gb5768Colors.white,
      secondaryColor: Gb5768Colors.black,
      borderColor: Gb5768Colors.red,
      assetPath: '$_assetBase/no_uturn.svg',
    ),
    TrafficSign(
      id: 'pro-no-parking',
      name: '禁止长时停车',
      code: code,
      category: SignCategory.prohibition,
      shape: SignShape.circle,
      primaryColor: Gb5768Colors.white,
      secondaryColor: Gb5768Colors.blue,
      borderColor: Gb5768Colors.red,
      assetPath: '$_assetBase/no_parking.svg',
      symbol: SignSymbol.noParking,
    ),
    TrafficSign(
      id: 'pro-no-stopping',
      name: '禁止停车',
      code: code,
      category: SignCategory.prohibition,
      shape: SignShape.circle,
      primaryColor: Gb5768Colors.blue,
      secondaryColor: Gb5768Colors.red,
      borderColor: Gb5768Colors.red,
      assetPath: '$_assetBase/no_stopping.svg',
      symbol: SignSymbol.noParking,
    ),
    TrafficSign(
      id: 'pro-no-honking',
      name: '禁止鸣喇叭',
      code: code,
      category: SignCategory.prohibition,
      shape: SignShape.circle,
      primaryColor: Gb5768Colors.white,
      secondaryColor: Gb5768Colors.black,
      borderColor: Gb5768Colors.red,
      assetPath: '$_assetBase/no_honking.svg',
      symbol: SignSymbol.noHonking,
    ),
    TrafficSign(
      id: 'pro-speed-limit-40',
      name: '限制速度 40',
      code: code,
      category: SignCategory.prohibition,
      shape: SignShape.circle,
      primaryColor: Gb5768Colors.white,
      secondaryColor: Gb5768Colors.red,
      borderColor: Gb5768Colors.red,
      assetPath: '$_assetBase/speed_limit_40.svg',
      symbol: SignSymbol.speedLimit,
      value: '40',
    ),
    TrafficSign(
      id: 'pro-speed-limit-60',
      name: '限制速度 60',
      code: code,
      category: SignCategory.prohibition,
      shape: SignShape.circle,
      primaryColor: Gb5768Colors.white,
      secondaryColor: Gb5768Colors.red,
      borderColor: Gb5768Colors.red,
      assetPath: '$_assetBase/speed_limit_60.svg',
      symbol: SignSymbol.speedLimit,
      value: '60',
    ),
    TrafficSign(
      id: 'pro-end-speed-limit',
      name: '解除限制速度',
      code: code,
      category: SignCategory.prohibition,
      shape: SignShape.circle,
      primaryColor: Gb5768Colors.white,
      secondaryColor: Gb5768Colors.black,
      borderColor: Gb5768Colors.black,
      assetPath: '$_assetBase/end_speed_limit.svg',
      symbol: SignSymbol.speedLimit,
    ),
    TrafficSign(
      id: 'pro-no-overtaking',
      name: '禁止超车',
      code: code,
      category: SignCategory.prohibition,
      shape: SignShape.circle,
      primaryColor: Gb5768Colors.white,
      secondaryColor: Gb5768Colors.black,
      borderColor: Gb5768Colors.red,
      assetPath: '$_assetBase/no_overtaking.svg',
    ),
    TrafficSign(
      id: 'pro-end-no-overtaking',
      name: '解除禁止超车',
      code: code,
      category: SignCategory.prohibition,
      shape: SignShape.circle,
      primaryColor: Gb5768Colors.white,
      secondaryColor: Gb5768Colors.black,
      borderColor: Gb5768Colors.black,
      assetPath: '$_assetBase/end_no_overtaking.svg',
    ),
    TrafficSign(
      id: 'pro-max-width-2_5',
      name: '限制宽度 2.5m',
      code: code,
      category: SignCategory.prohibition,
      shape: SignShape.circle,
      primaryColor: Gb5768Colors.white,
      secondaryColor: Gb5768Colors.red,
      borderColor: Gb5768Colors.red,
      assetPath: '$_assetBase/max_width_2_5.svg',
      value: '2.5m',
    ),
    TrafficSign(
      id: 'pro-max-height-3_5',
      name: '限制高度 3.5m',
      code: code,
      category: SignCategory.prohibition,
      shape: SignShape.circle,
      primaryColor: Gb5768Colors.white,
      secondaryColor: Gb5768Colors.red,
      borderColor: Gb5768Colors.red,
      assetPath: '$_assetBase/max_height_3_5.svg',
      value: '3.5m',
    ),
    TrafficSign(
      id: 'pro-max-weight-20',
      name: '限制质量 20t',
      code: code,
      category: SignCategory.prohibition,
      shape: SignShape.circle,
      primaryColor: Gb5768Colors.white,
      secondaryColor: Gb5768Colors.red,
      borderColor: Gb5768Colors.red,
      assetPath: '$_assetBase/max_weight_20.svg',
      value: '20t',
    ),
    TrafficSign(
      id: 'pro-max-axle-10',
      name: '限制轴重 10t',
      code: code,
      category: SignCategory.prohibition,
      shape: SignShape.circle,
      primaryColor: Gb5768Colors.white,
      secondaryColor: Gb5768Colors.red,
      borderColor: Gb5768Colors.red,
      assetPath: '$_assetBase/max_axle_10.svg',
      value: '10t',
    ),
    TrafficSign(
      id: 'pro-checkpoint',
      name: '停车检查',
      code: code,
      category: SignCategory.prohibition,
      shape: SignShape.rectangle,
      primaryColor: Gb5768Colors.white,
      secondaryColor: Gb5768Colors.red,
      borderColor: Gb5768Colors.red,
      assetPath: '$_assetBase/checkpoint.svg',
    ),
    TrafficSign(
      id: 'pro-no-hazmat',
      name: '禁止运输危险物品车辆驶入',
      code: code,
      category: SignCategory.prohibition,
      shape: SignShape.circle,
      primaryColor: Gb5768Colors.white,
      secondaryColor: Gb5768Colors.black,
      borderColor: Gb5768Colors.red,
      assetPath: '$_assetBase/no_hazmat.svg',
    ),
  ];

  static List<TrafficSign> get warningSigns => const [
    TrafficSign(
      id: 'warn-crossroad',
      name: '十字交叉',
      code: code,
      category: SignCategory.warning,
      shape: SignShape.triangle,
      primaryColor: Gb5768Colors.yellow,
      secondaryColor: Gb5768Colors.black,
      borderColor: Gb5768Colors.black,
      assetPath: '$_assetBase/crossroad_warning.svg',
      symbol: SignSymbol.crossroad,
    ),
    TrafficSign(
      id: 'warn-pedestrian',
      name: '注意行人',
      code: code,
      category: SignCategory.warning,
      shape: SignShape.triangle,
      primaryColor: Gb5768Colors.yellow,
      secondaryColor: Gb5768Colors.black,
      borderColor: Gb5768Colors.black,
      assetPath: '$_assetBase/pedestrian_warning.svg',
      symbol: SignSymbol.pedestrianCrossing,
    ),
    TrafficSign(
      id: 'warn-children',
      name: '注意儿童',
      code: code,
      category: SignCategory.warning,
      shape: SignShape.triangle,
      primaryColor: Gb5768Colors.yellow,
      secondaryColor: Gb5768Colors.black,
      borderColor: Gb5768Colors.black,
      assetPath: '$_assetBase/children_warning.svg',
      symbol: SignSymbol.children,
    ),
    TrafficSign(
      id: 'warn-work',
      name: '施工',
      code: code,
      category: SignCategory.warning,
      shape: SignShape.triangle,
      primaryColor: Gb5768Colors.yellow,
      secondaryColor: Gb5768Colors.black,
      borderColor: Gb5768Colors.black,
      assetPath: '$_assetBase/road_work.svg',
      symbol: SignSymbol.roadWork,
    ),
    TrafficSign(
      id: 'warn-t-junction',
      name: 'T 形交叉',
      code: code,
      category: SignCategory.warning,
      shape: SignShape.triangle,
      primaryColor: Gb5768Colors.yellow,
      secondaryColor: Gb5768Colors.black,
      borderColor: Gb5768Colors.black,
      assetPath: '$_assetBase/t_junction_warning.svg',
      symbol: SignSymbol.tJunction,
    ),
    TrafficSign(
      id: 'warn-sharp-left',
      name: '向左急弯',
      code: code,
      category: SignCategory.warning,
      shape: SignShape.triangle,
      primaryColor: Gb5768Colors.yellow,
      secondaryColor: Gb5768Colors.black,
      borderColor: Gb5768Colors.black,
      assetPath: '$_assetBase/sharp_curve_left.svg',
      symbol: SignSymbol.sharpCurveLeft,
    ),
    TrafficSign(
      id: 'warn-sharp-right',
      name: '向右急弯',
      code: code,
      category: SignCategory.warning,
      shape: SignShape.triangle,
      primaryColor: Gb5768Colors.yellow,
      secondaryColor: Gb5768Colors.black,
      borderColor: Gb5768Colors.black,
      assetPath: '$_assetBase/sharp_curve_right.svg',
      symbol: SignSymbol.sharpCurveRight,
    ),
    TrafficSign(
      id: 'warn-slippery',
      name: '路面湿滑',
      code: code,
      category: SignCategory.warning,
      shape: SignShape.triangle,
      primaryColor: Gb5768Colors.yellow,
      secondaryColor: Gb5768Colors.black,
      borderColor: Gb5768Colors.black,
      assetPath: '$_assetBase/slippery.svg',
      symbol: SignSymbol.slippery,
    ),
    TrafficSign(
      id: 'warn-village',
      name: '村庄',
      code: code,
      category: SignCategory.warning,
      shape: SignShape.triangle,
      primaryColor: Gb5768Colors.yellow,
      secondaryColor: Gb5768Colors.black,
      borderColor: Gb5768Colors.black,
      assetPath: '$_assetBase/village_warning.svg',
    ),
    TrafficSign(
      id: 'warn-tunnel',
      name: '隧道',
      code: code,
      category: SignCategory.warning,
      shape: SignShape.triangle,
      primaryColor: Gb5768Colors.yellow,
      secondaryColor: Gb5768Colors.black,
      borderColor: Gb5768Colors.black,
      assetPath: '$_assetBase/tunnel_warning.svg',
    ),
    TrafficSign(
      id: 'warn-signal',
      name: '注意信号灯',
      code: code,
      category: SignCategory.warning,
      shape: SignShape.triangle,
      primaryColor: Gb5768Colors.yellow,
      secondaryColor: Gb5768Colors.black,
      borderColor: Gb5768Colors.black,
      assetPath: '$_assetBase/signal_warning.svg',
    ),
  ];

  static List<TrafficSign> get mandatorySigns => const [
    TrafficSign(
      id: 'man-straight',
      name: '直行',
      code: code,
      category: SignCategory.mandatory,
      shape: SignShape.circle,
      primaryColor: Gb5768Colors.blue,
      secondaryColor: Gb5768Colors.white,
      assetPath: '$_assetBase/straight.svg',
      symbol: SignSymbol.straightAhead,
    ),
    TrafficSign(
      id: 'man-left',
      name: '向左转弯',
      code: code,
      category: SignCategory.mandatory,
      shape: SignShape.circle,
      primaryColor: Gb5768Colors.blue,
      secondaryColor: Gb5768Colors.white,
      assetPath: '$_assetBase/turn_left.svg',
      symbol: SignSymbol.turnLeft,
    ),
    TrafficSign(
      id: 'man-right',
      name: '向右转弯',
      code: code,
      category: SignCategory.mandatory,
      shape: SignShape.circle,
      primaryColor: Gb5768Colors.blue,
      secondaryColor: Gb5768Colors.white,
      assetPath: '$_assetBase/turn_right.svg',
      symbol: SignSymbol.turnRight,
    ),
    TrafficSign(
      id: 'man-straight-left',
      name: '直行和向左转弯',
      code: code,
      category: SignCategory.mandatory,
      shape: SignShape.circle,
      primaryColor: Gb5768Colors.blue,
      secondaryColor: Gb5768Colors.white,
      assetPath: '$_assetBase/straight_or_left.svg',
      symbol: SignSymbol.straightOrLeft,
    ),
    TrafficSign(
      id: 'man-straight-right',
      name: '直行和向右转弯',
      code: code,
      category: SignCategory.mandatory,
      shape: SignShape.circle,
      primaryColor: Gb5768Colors.blue,
      secondaryColor: Gb5768Colors.white,
      assetPath: '$_assetBase/straight_or_right.svg',
      symbol: SignSymbol.straightOrRight,
    ),
    TrafficSign(
      id: 'man-keep-left',
      name: '靠左侧道路行驶',
      code: code,
      category: SignCategory.mandatory,
      shape: SignShape.circle,
      primaryColor: Gb5768Colors.blue,
      secondaryColor: Gb5768Colors.white,
      assetPath: '$_assetBase/keep_left.svg',
      symbol: SignSymbol.keepLeft,
    ),
    TrafficSign(
      id: 'man-keep-right',
      name: '靠右侧道路行驶',
      code: code,
      category: SignCategory.mandatory,
      shape: SignShape.circle,
      primaryColor: Gb5768Colors.blue,
      secondaryColor: Gb5768Colors.white,
      assetPath: '$_assetBase/keep_right.svg',
      symbol: SignSymbol.keepRight,
    ),
    TrafficSign(
      id: 'man-roundabout',
      name: '环岛行驶',
      code: code,
      category: SignCategory.mandatory,
      shape: SignShape.circle,
      primaryColor: Gb5768Colors.blue,
      secondaryColor: Gb5768Colors.white,
      assetPath: '$_assetBase/roundabout.svg',
      symbol: SignSymbol.roundabout,
    ),
    TrafficSign(
      id: 'man-walk',
      name: '步行',
      code: code,
      category: SignCategory.mandatory,
      shape: SignShape.circle,
      primaryColor: Gb5768Colors.blue,
      secondaryColor: Gb5768Colors.white,
      assetPath: '$_assetBase/walk.svg',
      symbol: SignSymbol.walk,
    ),
  ];

  static List<TrafficSign> get indicationSigns => const [
    TrafficSign(
      id: 'ind-parking',
      name: '停车场',
      code: code,
      category: SignCategory.indication,
      shape: SignShape.square,
      primaryColor: Gb5768Colors.blue,
      secondaryColor: Gb5768Colors.white,
      assetPath: '$_assetBase/parking.svg',
      symbol: SignSymbol.parking,
    ),
    TrafficSign(
      id: 'ind-hospital',
      name: '医院',
      code: code,
      category: SignCategory.indication,
      shape: SignShape.square,
      primaryColor: Gb5768Colors.blue,
      secondaryColor: Gb5768Colors.white,
      assetPath: '$_assetBase/hospital.svg',
      symbol: SignSymbol.hospital,
    ),
  ];

  static List<TrafficSign> get informationSigns => chinaInformationSigns;

  static Map<SignCategory, List<TrafficSign>> get groupedByCategory => {
    SignCategory.prohibition: prohibitionSigns,
    SignCategory.warning: warningSigns,
    SignCategory.mandatory: mandatorySigns,
    SignCategory.indication: indicationSigns,
    SignCategory.information: informationSigns,
  };

  static TrafficSign? findById(String id) {
    for (final sign in allSigns) {
      if (sign.id == id) {
        return sign;
      }
    }
    return null;
  }
}
